"""Training Studio presets — recent history + named saves.

Captures the *full* Step 1-3 state of the Training Studio wizard so
the user can come back later and re-train with the same recipe in one
click. Two flavors:

  * **Recent** (auto-history): the last 3 ``Start Training`` invocations
    are pushed onto a ring buffer. No naming required — they're shown
    in the preset combo with a relative-time label ("2h ago").
  * **Named** (user-saved): the user explicitly clicks "💾 Save as
    preset…" and gives the recipe a name. Stored separately so they
    don't get evicted by the recent-cap.

Both kinds are persisted as JSON in ``~/.creativeos/training_presets.json``.
The schema is forward-compatible: unknown fields are preserved on
load and written back on save, so older builds reading newer files
won't lose data.
"""

from __future__ import annotations

import json
from dataclasses import dataclass, field, asdict
from datetime import datetime
from pathlib import Path
from typing import Any, Dict, List, Optional


PRESETS_FILE = Path.home() / ".creativeos" / "training_presets.json"
RECENT_CAP = 3  # ring-buffer size for auto-history


@dataclass
class TrainingPreset:
    """A snapshot of the Training Studio wizard state.

    ``name`` is the display label. For named presets it's user-given;
    for recent entries it's autogenerated (e.g. "horror-novelist · 02-14
    14:32"). The combo distinguishes the two by the ``is_recent`` flag.
    """

    name: str = ""
    timestamp: str = ""           # ISO datetime; written on capture
    is_recent: bool = False       # True for auto-history, False for saved

    # ── Step 1: describe + sources ──
    description: str = ""
    goal: str = ""                # voice/plot/qa/worldbuilding/character/both
    medium: str = ""              # books/movies/tv/short/mixed

    src_rephrase: bool = True
    src_chat_writing: bool = True
    src_chat_general: bool = False
    src_corpus: bool = True
    src_agent: bool = False
    src_worldbuilding: bool = False
    src_character: bool = False
    src_plot: bool = False

    upload_voice: str = ""        # voice tag for any future corpus uploads
    upload_genre: str = ""        # genre tag

    export_format: str = "instruction"     # instruction|chat|dpo|raw
    export_min_rating: str = "good"        # neutral|good|excellent

    # ── Step 2: base model ──
    base_model: str = "google/gemma-2-2b-it"
    continue_from: str = ""       # path to a trained model dir; empty = fresh

    # ── Step 3: hyperparams ──
    model_name: str = "my-voice-v1"
    epochs: int = 2
    learning_rate: float = 2e-4
    batch_size: int = 1
    lora_r: int = 8
    use_qlora: bool = False
    train_min_rating: str = "good"

    # Forward-compat sink — unknown keys land here on load and are
    # written back on save.
    extras: Dict[str, Any] = field(default_factory=dict)

    def display_label(self) -> str:
        """Human-readable label for the preset combo."""
        if self.is_recent:
            return f"⏱ {self.name}"
        return f"⭐ {self.name}"

    def to_dict(self) -> Dict[str, Any]:
        d = asdict(self)
        # Pull extras up to top level so old loaders see them
        extras = d.pop("extras", {}) or {}
        d.update(extras)
        return d

    @classmethod
    def from_dict(cls, data: Dict[str, Any]) -> "TrainingPreset":
        if not isinstance(data, dict):
            return cls()
        known = set(cls.__dataclass_fields__.keys())
        kwargs = {k: v for k, v in data.items() if k in known}
        extras = {k: v for k, v in data.items() if k not in known}
        kwargs["extras"] = extras
        return cls(**kwargs)


def _load_raw() -> Dict[str, List[Dict[str, Any]]]:
    """Read the on-disk JSON. Returns the canonical {recent,saved} shape."""
    if not PRESETS_FILE.exists():
        return {"recent": [], "saved": []}
    try:
        with open(PRESETS_FILE, "r", encoding="utf-8") as f:
            data = json.load(f)
        if not isinstance(data, dict):
            return {"recent": [], "saved": []}
        return {
            "recent": list(data.get("recent", [])),
            "saved": list(data.get("saved", [])),
        }
    except Exception as e:
        print(f"[training_presets] could not read {PRESETS_FILE}: {e}")
        return {"recent": [], "saved": []}


def _write_raw(data: Dict[str, List[Dict[str, Any]]]) -> bool:
    try:
        PRESETS_FILE.parent.mkdir(parents=True, exist_ok=True)
        with open(PRESETS_FILE, "w", encoding="utf-8") as f:
            json.dump(data, f, indent=2, ensure_ascii=False)
        return True
    except Exception as e:
        print(f"[training_presets] could not save: {e}")
        return False


def load_recent() -> List[TrainingPreset]:
    """Return the last N recent presets (most-recent first)."""
    return [TrainingPreset.from_dict(d) for d in _load_raw()["recent"]]


def load_saved() -> List[TrainingPreset]:
    """Return user-named presets in save order."""
    return [TrainingPreset.from_dict(d) for d in _load_raw()["saved"]]


def add_recent(preset: TrainingPreset) -> None:
    """Push ``preset`` onto the recent ring buffer, capped at RECENT_CAP.

    Always-fresh timestamp + ``is_recent=True`` are forced on the way
    in. If a preset with an identical name already exists in the
    history (e.g. retraining the same model), the older entry is
    dropped first so the buffer stays informative.
    """
    preset.timestamp = datetime.now().isoformat(timespec="seconds")
    preset.is_recent = True
    raw = _load_raw()
    recents = [d for d in raw["recent"]
               if d.get("name") != preset.name]
    recents.insert(0, preset.to_dict())
    raw["recent"] = recents[:RECENT_CAP]
    _write_raw(raw)


def save_named(preset: TrainingPreset, name: Optional[str] = None) -> None:
    """Persist a user-named preset (overwriting one with the same name)."""
    if name is not None:
        preset.name = name
    preset.is_recent = False
    preset.timestamp = datetime.now().isoformat(timespec="seconds")
    raw = _load_raw()
    saved = [d for d in raw["saved"]
             if d.get("name") != preset.name]
    saved.append(preset.to_dict())
    raw["saved"] = saved
    _write_raw(raw)


def delete_named(name: str) -> bool:
    """Remove a named preset. Returns True if anything was removed."""
    raw = _load_raw()
    before = len(raw["saved"])
    raw["saved"] = [d for d in raw["saved"] if d.get("name") != name]
    changed = len(raw["saved"]) != before
    if changed:
        _write_raw(raw)
    return changed


def find_preset(name: str, *, recent: bool) -> Optional[TrainingPreset]:
    """Look up a preset by name in either bucket. Returns None on miss."""
    bucket = load_recent() if recent else load_saved()
    for p in bucket:
        if p.name == name:
            return p
    return None


def _humanize_age(timestamp: str) -> str:
    """Convert an ISO timestamp to a short ‘2h ago’ label for the combo."""
    try:
        ts = datetime.fromisoformat(timestamp)
    except Exception:
        return ""
    delta = datetime.now() - ts
    sec = int(delta.total_seconds())
    if sec < 60:
        return "just now"
    if sec < 3600:
        return f"{sec // 60}m ago"
    if sec < 86400:
        return f"{sec // 3600}h ago"
    return f"{sec // 86400}d ago"
