"""Data models for the Video Studio module.

The studio is a node-graph view: each ``Scene`` is a card; ``SceneHop``
links connect cards. Each scene can have many generated ``VideoClip``s
(from one or several backend runs); the user marks a favorite and can
delete the rest. ``CharacterReference`` carries a reusable description
+ seed so character appearance stays consistent across clips.

``VideoStudio`` is the root container that lives on ``WriterProject``.
"""

from __future__ import annotations

from datetime import datetime
from typing import Dict, List, Optional, Tuple
from uuid import uuid4

from pydantic import BaseModel, Field


class VideoClip(BaseModel):
    """One generated media file attached to a scene.

    Despite the historical name, a "clip" can be either a video file
    (``clip_type="video"``) or a still image (``clip_type="image_still"``)
    shown for ``duration_seconds``. The studio keeps the path, not
    the bytes. Backends write the file + a JSON sidecar with the
    prompt + backend + parameters.
    """
    id: str = Field(default_factory=lambda: f"clip_{uuid4().hex[:10]}")
    file_path: str = ""
    backend: str = ""
    prompt_at_generation: str = ""
    # For videos this is the actual clip length; for image stills
    # this is how long the still should be displayed when the scene
    # plays / is stitched into the final cut.
    duration_seconds: float = 0.0
    seed: Optional[int] = None
    created_at: datetime = Field(default_factory=datetime.now)
    # Sidecar metadata path (JSON) for inspection / debugging.
    sidecar_path: str = ""
    # True for backends that produced a placeholder rather than
    # actual rendered media. The UI labels these distinctly so the
    # user knows it's not a real render.
    is_placeholder: bool = False
    # "video" (default, backwards compatible) or "image_still".
    # Image stills are converted to a short video clip by the
    # stitcher using their ``duration_seconds`` as the display time.
    clip_type: str = "video"
    notes: str = ""


class Scene(BaseModel):
    """A single scene card on the studio canvas.

    Position is grid-cell coordinates, not pixels. The canvas
    converts to pixels at render time so changing the cell size
    doesn't move scenes.
    """
    id: str = Field(default_factory=lambda: f"scene_{uuid4().hex[:10]}")
    name: str = ""
    description: str = ""           # human-readable scene description
    prompt: str = ""                # video-generation prompt
    # Optional anchor back to a chapter — lets the AI director pull
    # focused RAG / plot context when the user asks for help editing.
    chapter_id: Optional[str] = None
    chapter_number: Optional[int] = None
    # Characters present in the scene; used to attach reference info
    # at generation time so characters render consistently.
    character_refs: List[str] = Field(default_factory=list)
    # Generation outputs.
    clips: List[VideoClip] = Field(default_factory=list)
    favorite_clip_id: Optional[str] = None
    # Position on the canvas grid. (col, row) zero-indexed.
    grid_col: int = 0
    grid_row: int = 0
    # Per-scene target duration overrides the studio default. None
    # means "use VideoStudio.default_duration_seconds". Lets users
    # ask the LLM for a 15s establishing shot and a 4s reaction
    # beat in the same chapter without retuning the global default.
    target_duration_seconds: Optional[float] = None
    # Display time for image stills generated by an ImageBackend.
    # Separate field from ``target_duration_seconds`` because a
    # scene might have BOTH a video clip (for the live render) and
    # an image still (as a fallback or storyboard frame), each with
    # its own appropriate length.
    image_display_seconds: float = 4.0
    created_at: datetime = Field(default_factory=datetime.now)
    updated_at: datetime = Field(default_factory=datetime.now)

    def effective_duration(
        self, studio_default: float,
    ) -> float:
        """Resolve the duration this scene should render at.

        ``target_duration_seconds`` wins when set; falls back to the
        studio's global default otherwise. Always returns a positive
        number ≥ 1.0 so backends don't get asked for 0-second clips.
        """
        if (self.target_duration_seconds is not None
                and self.target_duration_seconds > 0):
            return max(1.0, float(self.target_duration_seconds))
        return max(1.0, float(studio_default))

    def add_clip(self, clip: VideoClip) -> None:
        self.clips.append(clip)
        if self.favorite_clip_id is None:
            self.favorite_clip_id = clip.id
        self.updated_at = datetime.now()

    def remove_clip(self, clip_id: str) -> bool:
        before = len(self.clips)
        self.clips = [c for c in self.clips if c.id != clip_id]
        if self.favorite_clip_id == clip_id:
            self.favorite_clip_id = (
                self.clips[0].id if self.clips else None)
        self.updated_at = datetime.now()
        return len(self.clips) != before

    def favorite_clip(self) -> Optional[VideoClip]:
        if not self.favorite_clip_id:
            return self.clips[0] if self.clips else None
        for c in self.clips:
            if c.id == self.favorite_clip_id:
                return c
        return self.clips[0] if self.clips else None


class SceneHop(BaseModel):
    """A directed edge from one scene to another on the canvas.

    Hops are the "connect cards" the user described. They convey
    sequence/flow — e.g., scene A comes before B. Hops are used by
    the stitcher to determine assembly order when the user picks
    "stitch all favorites along this path".
    """
    id: str = Field(default_factory=lambda: f"hop_{uuid4().hex[:10]}")
    from_scene_id: str
    to_scene_id: str
    label: str = ""  # optional — e.g., "then", "cut to", "flashback"


class CharacterReference(BaseModel):
    """Reusable character info attached at video-generation time.

    A backend that supports character grounding receives this whole
    block as context, ensuring the character renders the same way
    across scenes / chapters. ``seed`` is for backends that support
    deterministic generation given a seed.
    """
    id: str = Field(default_factory=lambda: f"chref_{uuid4().hex[:10]}")
    name: str
    description: str = ""
    appearance_prompt: str = ""    # terse appearance for the backend
    reference_image_path: str = ""  # optional reference still
    seed: Optional[int] = None      # for deterministic backends
    notes: str = ""


class VideoStudio(BaseModel):
    """Root container — lives on the WriterProject.

    Scenes and hops are stored as flat lists; lookups by id happen
    through helpers. ``backend_preference`` records the last
    backend the user selected so we restore it across sessions.
    ``grid_dimensions`` lets the user resize the canvas grid.
    """
    scenes: List[Scene] = Field(default_factory=list)
    hops: List[SceneHop] = Field(default_factory=list)
    character_references: List[CharacterReference] = Field(
        default_factory=list)
    backend_preference: str = ""
    grid_cols: int = 6   # canvas grid column count
    grid_rows: int = 8   # canvas grid row count
    # Default video length the AI director should aim for, in
    # seconds. Should be "enough to read the scene" — the studio's
    # design goal.
    default_duration_seconds: float = 8.0

    # ---- scene helpers ----
    def get_scene(self, scene_id: str) -> Optional[Scene]:
        for s in self.scenes:
            if s.id == scene_id:
                return s
        return None

    def add_scene(self, scene: Scene) -> Scene:
        # Place at first free cell if the proposed cell is occupied.
        if self._cell_occupied(scene.grid_col, scene.grid_row,
                               exclude_id=scene.id):
            col, row = self._first_free_cell()
            scene.grid_col, scene.grid_row = col, row
        self.scenes.append(scene)
        return scene

    def delete_scene(self, scene_id: str) -> bool:
        before = len(self.scenes)
        self.scenes = [s for s in self.scenes if s.id != scene_id]
        # Cascade: drop hops that touched the deleted scene.
        self.hops = [
            h for h in self.hops
            if h.from_scene_id != scene_id and h.to_scene_id != scene_id]
        return len(self.scenes) != before

    def move_scene(self, scene_id: str, col: int, row: int) -> bool:
        s = self.get_scene(scene_id)
        if s is None:
            return False
        # Bound check + occupancy check.
        col = max(0, min(self.grid_cols - 1, col))
        row = max(0, min(self.grid_rows - 1, row))
        if self._cell_occupied(col, row, exclude_id=scene_id):
            return False
        s.grid_col, s.grid_row = col, row
        s.updated_at = datetime.now()
        return True

    def _cell_occupied(
        self, col: int, row: int, exclude_id: str = "",
    ) -> bool:
        for s in self.scenes:
            if s.id == exclude_id:
                continue
            if s.grid_col == col and s.grid_row == row:
                return True
        return False

    def _first_free_cell(self) -> Tuple[int, int]:
        for row in range(self.grid_rows):
            for col in range(self.grid_cols):
                if not self._cell_occupied(col, row):
                    return col, row
        # All cells full — expand grid by one row and use the first
        # cell of the new row.
        self.grid_rows += 1
        return 0, self.grid_rows - 1

    # ---- hop helpers ----
    def add_hop(
        self,
        from_id: str,
        to_id: str,
        label: str = "",
    ) -> Optional[SceneHop]:
        if from_id == to_id:
            return None  # no self-loops
        if not self.get_scene(from_id) or not self.get_scene(to_id):
            return None
        # Dedupe: don't add a duplicate hop with the same direction.
        for h in self.hops:
            if h.from_scene_id == from_id and h.to_scene_id == to_id:
                return h
        hop = SceneHop(
            from_scene_id=from_id, to_scene_id=to_id, label=label)
        self.hops.append(hop)
        return hop

    def delete_hop(self, hop_id: str) -> bool:
        before = len(self.hops)
        self.hops = [h for h in self.hops if h.id != hop_id]
        return len(self.hops) != before

    def hops_out_of(self, scene_id: str) -> List[SceneHop]:
        return [h for h in self.hops if h.from_scene_id == scene_id]

    def hops_into(self, scene_id: str) -> List[SceneHop]:
        return [h for h in self.hops if h.to_scene_id == scene_id]

    # ---- character refs ----
    def get_character_reference(
        self, name: str,
    ) -> Optional[CharacterReference]:
        norm = (name or "").strip().lower()
        if not norm:
            return None
        for ref in self.character_references:
            if ref.name.strip().lower() == norm:
                return ref
        return None

    def upsert_character_reference(
        self, ref: CharacterReference,
    ) -> CharacterReference:
        for i, existing in enumerate(self.character_references):
            if existing.id == ref.id:
                self.character_references[i] = ref
                return ref
        self.character_references.append(ref)
        return ref

    # ---- stitching path ----
    def topological_order_starting_at(
        self, start_id: str,
    ) -> List[Scene]:
        """Walk outgoing hops from ``start_id`` in BFS order.

        Used by the stitcher when the user picks "stitch from here
        along the hops". Cycle-safe: visited set prevents revisits.
        """
        ordered: List[Scene] = []
        visited: set = set()
        queue: List[str] = [start_id]
        while queue:
            sid = queue.pop(0)
            if sid in visited:
                continue
            visited.add(sid)
            s = self.get_scene(sid)
            if s is None:
                continue
            ordered.append(s)
            for h in self.hops_out_of(sid):
                if h.to_scene_id not in visited:
                    queue.append(h.to_scene_id)
        return ordered
